apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-dummy-app
  labels:
    app: dummy-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: dummy-app
  template:
    metadata:
      labels:
        app: dummy-app
    spec:
      containers:
        - name: dummy-app
          # Harness resolves this expression at runtime to the full ECR image path + selected tag
          # e.g. 664418987337.dkr.ecr.us-west-2.amazonaws.com/sruthi/dummy-example:a1b2c3d
          image: <+artifact.image>
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
